name: build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.x.x        
    
    - name: Build
      run: dotnet build --verbosity minimal
    
    - name: Docker Compose Up
      run: docker compose -f tests/NBomber.Sinks.InfluxDB.Tests/Docker/docker-compose.yaml up -d --wait

    - name: Test
      run: dotnet test --project tests/NBomber.Sinks.InfluxDB.Tests --no-build
